# Generated by Django 4.2.6 on 2023-10-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('author', models.CharField(max_length=512)),
                ('original_language', models.CharField(max_length=256)),
                ('year_published', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('genre', models.CharField(max_length=256)),
                ('cover_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
