# Generated by Django 4.2.6 on 2023-10-24 14:33

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):
    def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "initial_books.json")

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]

