# Generated by Django 4.2.6 on 2023-10-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_load_book_fixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(null=True, upload_to="input/cover"),
        ),
    ]
