# Generated by Django 4.2.6 on 2023-10-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookmarked',
        ),
    ]
