# Generated by Django 4.2.6 on 2023-10-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_book_cover_image"),
        ("main", "0004_remove_book_bookmarked"),
    ]

    operations = []
