# Generated by Django 4.2.8 on 2023-12-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_merge_20231029_1355"),
        ("main", "0005_review"),
    ]

    operations = []
