# Generated by Django 4.2.6 on 2023-10-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20231029_1355'),
        ('main', '0005_review'),
    ]

    operations = [
    ]
