# Generated by Django 4.2.6 on 2023-10-29 17:33

import logging
import environ
from django.db import migrations

logger = logging.getLogger(__name__)

def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    # env = environ.Env()
    USERNAME = "superpals"# env.str("ADMIN_USERNAME")
    PASSWORD = "utslancar"# env.str("ADMIN_PASSWORD")
    EMAIL = "superpals@pbp.com"# env.str("ADMIN_EMAIL")

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
            username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
    else:
        logger.info("Superuser already created!")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_0005_merge_20231029_1355_0005_review'),
    ]

    operations = [
    ]
