# Generated by Django 4.2.6 on 2023-10-29 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("author", models.CharField(max_length=512)),
                ("original_language", models.CharField(max_length=256)),
                ("year_published", models.IntegerField()),
                ("sales", models.IntegerField()),
                ("genre", models.CharField(max_length=256)),
                ("cover_image", models.ImageField(null=True, upload_to="input/cover")),
                ("request_date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
