# Generated by Django 4.2.6 on 2023-10-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_load_book_fixture'),
        ('user_profile', '0002_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarkedbooks',
            field=models.ManyToManyField(to='main.book'),
        ),
    ]
