# Generated by Django 4.2.6 on 2023-10-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_bookmarkedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default=True, max_length=255),
        ),
    ]