# Generated by Django 4.2.6 on 2023-10-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_book_bookmarked'),
        ('user_profile', '0004_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookmarkedbooks',
            field=models.ManyToManyField(blank=True, to='main.book'),
        ),
    ]
