# Generated by Django 4.2.8 on 2023-12-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0008_userprofile_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_admin",
        ),
    ]
