# Generated by Django 4.2.8 on 2023-12-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0008_alter_userprofile_nickname"),
        ("user_profile", "0008_userprofile_isadmin"),
        ("user_profile", "0009_remove_userprofile_is_admin"),
    ]

    operations = []
