# Generated by Django 4.2.6 on 2023-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookswap',
            name='book_name',
        ),
        migrations.AddField(
            model_name='bookswap',
            name='name',
            field=models.CharField(choices=[(1, 'A Tale of Two Cities'), (2, 'The Little Prince (Le Petit Prince)'), (3, "Harry Potter and the Philosopher's Stone"), (4, 'And Then There Were None'), (5, 'Dream of the Red Chamber (紅樓夢)'), (6, 'The Hobbit'), (7, 'The Lion, the Witch and the Wardrobe'), (8, 'She: A History of Adventure'), (9, 'Vardi Wala Gunda (वर्दी वाला गुंडा)'), (10, 'The Da Vinci Code'), (11, 'Harry Potter and the Chamber of Secrets'), (12, 'Harry Potter and the Prisoner of Azkaban'), (13, 'Harry Potter and the Goblet of Fire'), (14, 'Harry Potter and the Order of the Phoenix'), (15, 'Harry Potter and the Half-Blood Prince'), (16, 'Harry Potter and the Deathly Hallows'), (17, 'The Alchemist (O Alquimista)'), (18, 'The Catcher in the Rye'), (19, 'The Bridges of Madison County'), (20, 'Ben-Hur: A Tale of the Christ'), (21, 'You Can Heal Your Life'), (22, 'One Hundred Years of Solitude (Cien años de soledad)'), (23, 'Lolita'), (24, 'Heidi'), (25, 'The Common Sense Book of Baby and Child Care'), (26, 'Anne of Green Gables'), (27, 'Black Beauty'), (28, 'The Name of the Rose (Il Nome della Rosa)'), (29, 'The Eagle Has Landed'), (30, 'Watership Down'), (31, 'The Hite Report'), (32, "Charlotte's Web"), (33, 'The Ginger Man'), (34, 'The Tale of Peter Rabbit'), (35, 'Jonathan Livingston Seagull'), (36, 'The Very Hungry Caterpillar'), (37, 'A Message to Garcia'), (38, 'To Kill a Mockingbird'), (39, 'Flowers in the Attic'), (40, 'Cosmos'), (41, "Sophie's World (Sofies verden)"), (42, 'Angels & Demons'), (43, 'Kane and Abel'), (44, 'How the Steel Was Tempered (Как закалялась сталь)'), (45, 'War and Peace (Война и мир)'), (46, 'The Adventures of Pinocchio (Le avventure di Pinocchio)'), (47, 'The Diary of Anne Frank (Het Achterhuis)'), (48, 'Your Erroneous Zones'), (49, 'The Thorn Birds'), (50, 'The Purpose Driven Life'), (51, 'The Kite Runner'), (52, 'Valley of the Dolls'), (53, 'Alcoholics Anonymous Big Book'), (54, 'How to Win Friends and Influence People'), (55, 'The Great Gatsby'), (56, 'Gone with the Wind'), (57, 'Rebecca'), (58, 'Nineteen Eighty-Four'), (59, 'The Revolt of Mamie Stover'), (60, 'The Girl with the Dragon Tattoo (Män som hatar kvinnor)'), (61, 'The Lost Symbol'), (62, 'The Hunger Games'), (63, 'James and the Giant Peach'), (64, 'The Young Guard (Молодая гвардия)'), (65, 'Who Moved My Cheese?'), (66, 'A Brief History of Time'), (67, 'Paul et Virginie'), (68, 'Lust for Life'), (69, 'The Wind in the Willows'), (70, 'The 7 Habits of Highly Effective People'), (71, 'Virgin Soil Upturned (Поднятая целина)'), (72, 'The Celestine Prophecy'), (73, 'The Fault in Our Stars'), (74, 'The Girl on the Train'), (75, 'The Shack'), (76, 'Uncle Styopa (Дядя Стёпа)'), (77, 'The Godfather'), (78, 'Love Story'), (79, 'Catching Fire'), (80, 'Mockingjay'), (81, 'Kitchen (キッチン)'), (82, 'Andromeda Nebula (Туманность Андромеды)'), (83, 'Autobiography of a Yogi (योगी कथामृत)'), (84, 'Gone Girl'), (85, 'All Quiet on the Western Front (Im Westen nichts Neues)'), (86, 'The Bermuda Triangle'), (87, 'Things Fall Apart '), (88, 'Animal Farm '), (89, 'Wolf Totem (狼图腾)'), (90, 'The Happy Hooker: My Own Story'), (91, 'Jaws'), (92, 'Love You Forever'), (93, "The Women's Room"), (94, "What to Expect When You're Expecting"), (95, 'Adventures of Huckleberry Finn'), (96, 'The Secret Diary of Adrian Mole, Aged 13¾'), (97, 'Pride and Prejudice'), (98, 'Kon-Tiki: Across the Pacific in a Raft (Kon-Tiki ekspedisjonen)'), (99, 'The Good Soldier Švejk (Osudy dobrého vojáka Švejka za světové války)'), (100, 'Where the Wild Things Are')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='user',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='BookSwapAcc',
        ),
    ]
