# Generated by Django 4.2.7 on 2023-12-17 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20231030_0033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_swap', '0002_rename_message_bookswap_from_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookswap',
            name='have_book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='have_book', to='main.book'),
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='to_message',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='to_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
