# Generated by Django 4.2.6 on 2023-10-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0003_alter_bookswap_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSwapAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('acc_user', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
