# Generated by Django 4.2.6 on 2023-10-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0004_bookswapacc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookswapacc',
            name='author',
        ),
    ]
