# Generated by Django 4.2.7 on 2023-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0004_alter_bookswap_have_book_alter_bookswap_want_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookswap',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
