# Generated by Django 4.2.6 on 2023-10-29 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_swap', '0005_remove_bookswapacc_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookswapacc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookswapacc',
            name='user',
        ),
        migrations.AddField(
            model_name='bookswapacc',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_swap.bookswap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookswapacc',
            name='acc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
