# Generated by Django 4.2.6 on 2023-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0006_remove_bookswapacc_name_remove_bookswapacc_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookswapacc',
            old_name='request',
            new_name='book_swap',
        ),
        migrations.AlterField(
            model_name='bookswapacc',
            name='acc_user',
            field=models.CharField(max_length=150),
        ),
    ]
