# Generated by Django 4.2.7 on 2023-12-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0007_remove_bookswap_swap_id_bookswap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookswap',
            name='from_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='to_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
