# Generated by Django 4.2.6 on 2023-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0007_rename_request_bookswapacc_book_swap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookswap',
            name='swapped',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BookSwapAcc',
        ),
    ]
