# Generated by Django 4.2.6 on 2023-10-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_swap', '0008_bookswap_swapped_delete_bookswapacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookswap',
            name='acc_user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookswap',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
